services:
  server:
    image: postgrest/postgrest:v12.2.8
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGRST_OPENAPI_SERVER_PROXY_URI: ${POSTGREST_API_URL}
      PGRST_DB_ANON_ROLE: ${POSTGRES_USER}
      PGRST_DB_SCHEMA: ${POSTGRES_DB_SCHEMA}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./build/postgreSQL/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nicegui-app:
    image: python:3.11-slim
    ports:
      - "8080:8080"
    volumes:
      - ./nicegui_app.py:/app/nicegui_app.py:ro
    working_dir: /app
    command: >
      sh -c "
        pip install nicegui httpx &&
        python nicegui_app.py
      "
    depends_on:
      - server
      - db
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
