# .github/workflows/ci.yml

name: Continuous Integration

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install test dependencies
              run: pip install -r tests/requirements.txt

            - name: Start Docker services
              run: |
                  docker compose -f docker-compose.yaml -f docker-compose-dev.yaml --profile Frontend up -d

            - name: Wait for services to be healthy
              run: |
                  echo "Waiting for containers to be healthy..."
                  sleep 15 # A simple wait, as in the original script

            - name: Run pytest
              env:
                  PYTHONPATH: ${{ github.workspace }}
              run: pytest

            - name: Stop Docker services
              if: always() # This ensures cleanup runs even if tests fail
              run: |
                  docker compose -f docker-compose.yaml -f docker-compose-dev.yaml down --remove-orphans
